name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: BuildAPP
      run: dotnet build Application --configuration Release --no-restore    
    - name: BuildCommons
      run: dotnet build Commons --configuration Release --no-restore
    - name: BuildDal
      run: dotnet build DAL --configuration Release --no-restore
    - name: BuildUI
      run: dotnet build WebUI --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
